project_path =File.expand_path('..',File.dirname(__FILE__))
preferred_syntax = :sass
css_dir = 'assets/css'
sass_dir = 'assets/scss'
images_dir = 'assets/images'
javascripts_dir = 'assets/js'
relative_assets = true
line_comments = true
output_style = :compressed